### ISSUE TITLE
Customer page

### ISSUE THREAD

**Issue by coltenleidner** [markiragoldberg/cs-350-project#1]
- Make a form for customers to place an order
- Give a time estimate on the number of orders and type of order in database
- Completing the form should put the order in the database
- Error checking for orders to be placed at a specified time
- Need card information
- Able to order pizzas, calzones, salads, and soda
- Page for the history of the restaurant

**Comment by markiragoldberg** [comment]
:+1:

**Comment by markiragoldberg** [comment]
It's done.
